### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by zZzUnique** [tdh8316/Arduino-Projects#2]
안녕하세요.  공식 사이트에서 정보를 찾던 도중
작성자님께서 링크를 공유하신 댓글을 보게 되었는데
궁금해서 질문드립니다.

1. 오렌지보드와 우노보드 중 어떤 보드를 사용하셨는지
2. 소스코드를 보면 블루투스 연결하신 것 같은데 따로 블루투스 모듈을 사용하셨는지
3. lcd모듈 헤더파일을 잡지 못하는데 어떻게 해결하셨는지
입니다. 소스코드 공유해주셔서 감사합니다.

**Comment by tdh8316** [comment]
안녕하세요!

먼저, 4년 전 작성한 코드라 기억이 확실하지 않습니다. ㅠㅠ
정확하게 알려드리지 못해서 죄송하다는 말씀 먼저 드립니다.

1. 오렌지보드와 우노보드 중 어떤 보드를 사용하셨는지
 > 이 부분은 기억이 나지 않습니다... 오렌지보드에 관해 검색해보니 어떤 것을 사용해도 무방할 듯 합니다.
2. 소스코드를 보면 블루투스 연결하신 것 같은데 따로 블루투스 모듈을 사용하셨는지
 > 이것도 기억이 나지는 않습니다... 만약 블루투스가 내장된 오렌지파이를 사용했다면 내장된 블루투스를 사용했을 것이고, 그냥 아두이노 우노를 사용했다면 따로 블루투스 모듈을 사용했을 것입니다. 블루투스 모듈은 HC-06 등이 있습니다.
3. lcd모듈 헤더파일을 잡지 못하는데 어떻게 해결하셨는지
 > 소스코드를 살펴보니 LiquidCrystal_I2C 헤더를 못 찾았을 것 같은데, 해당 라이브러리는 추가로 설치가 필요한 라이브러리입니다. 아두이노 IDE의 라이브러리 매니저에서 해당 라이브러리를 설치해 주시면 됩니다.

감사합니다!

**Comment by zZzUnique** [comment]
답변 감사합니다. 남은 시간 좋은 하루 되세요!
